name: Deployment Reusable - Workflow

on:
    workflow_call:
      inputs:
        mongodb-uri:
          type: string
          required: true
        kubectl-version:
          description: Provide the required kubectl version
          type: string
          required: false
          default: v1.32.0
        k8s-manifest-dir:
          description: Directory with k8 manifest files
          type: string
          required: true
          default: kubernetes/
        environment:
          description: Provide the Deployment environment
          type: string
          required: true
        
      secrets:
        k8s-kubeconfig:
          required: true
        mongodb-password:
          required: true
  
      outputs:
        aplication_url:
          value: ${{jobs.reuse-deploy.outputs.APP_INGRESS_URL}}
        
jobs:
  reuse-deploy:
      environment:
        name: ${{inputs.environment}}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      outputs:
        APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 
          
        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v4
          with:
            version: '${{inputs.kubectl-version}}' # default is latest stable
          
        - name: Set KUBECONFIG
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.k8s-kubeconfig}}

        - name: Fetch Kubernetes cluster datails
          run: | 
            kubectl version
            echo -------------------------
            kubectl get nodes
        
        - name: Save Ingress controller IP as env Variable
          run: |
              echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> "$GITHUB_ENV"
        - name: Replace Tokens in manifest files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["${{inputs.k8s-manifest-dir}}*.yaml"]'
          env:
            NAMESPACE: ${{vars.NAMESPACE}}
            REPLICAS: ${{vars.REPLICAS}}
            IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/nana_python:${{github.sha}}
            INGRESS_IP: ${{env.INGRESS_IP}}

        - name: Check files
          run: |
            cat ${{inputs.k8s-manifest-dir}}*.yaml
        
        - name: Create Mongo db secret
          run: |
            kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{inputs.mongodb-uri}} \
              --from-literal=MONGO_USERNAME=${{vars.MONGO_USERNAME}} \
              --from-literal=MONGO_PASSWORD=${{secrets.mongodb-password}} \
              --save-config \
              --dry-run=client \
              -o yaml | kubectl apply -f -
        - name: Deploy to ${{inputs.environment}} Enviroment
          run: |
            kubectl apply -f ${{inputs.k8s-manifest-dir}}
        
        - name: Get ingress URL
          id: set-ingress-host-address
          run: |
            echo "APP_INGRESS_HOST=$(kubectl -n ${{vars.NAMESPACE}} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"